### ISSUE TITLE
default text size too small

### ISSUE THREAD

**Issue by riebling** [conix-center/ARENA#3]
In spite of setting the attribute which, when manually set in the A-Frame Scene Inspector, "does the right thing" to make text reasonable-sized (auto scaled based on how much text fits in a rectangle) - when drawn via MQTT message, it appears much smaller than in the Master branch.  It's a mystery!

**Comment by syreal17** [comment]
What's the attribute called?

**Comment by riebling** [comment]
Found & fixed; the attributes (e.g. 'width') being set are in a hierarchy, not as
```
setAttribute('width', 5)
```
but rather
```
setAttribute('text', 'width', 5)
```
the text above the head models is different because it is an `<a-text>` Component, (not `<a-entity>`) which supports the first syntax
