### ISSUE TITLE
Document Occulus Controller Buttons

### ISSUE THREAD

**Issue by anthonyrowe** [conix-center/ARENA#33]
Merge this google doc into the docs:
https://docs.google.com/document/d/1iJRTWJSE1Y3qHTrD9NaqzvqZXbmWhj8ZC0YL6cDvnno/edit?usp=sharing

**Comment by nampereira** [comment]
Done [here](https://arena.conix.io/content/xr/requirements.html#oculus-browser-quest-quest-2-and-more).
