### ISSUE TITLE
Dynamic setting-of-Physics not working

### ISSUE THREAD

**Issue by riebling** [conix-center/ARENA#5]
I guess it was a small miracle that it worked before, briefly. But now, trying to "turn on physics" via an 'update' message that sets the "dynamic-body" attribute of an object... doesn't seem to have any effect. But at least it doesn't cause the object to go shooting off to infinity(!) :)

**Comment by syreal17** [comment]
Huh, perhaps the persistence of location is actually locking objects into place in spite of physics "trying" to move them?

**Comment by riebling** [comment]
It's looking like the setting of the attribute never occurs, hence no action, no sign of it having ever been invoked. I need to figure out how the Entity-Component system works when dynamically manipulating things in memory vs. having them defined statically in HTML first; when you set a previously unset attribute, does that alter a Component or make it into a new kind of Component that now has more values that are settable? Specifically "dynamic-body" has a lot of other sub-attributes (values?) associated with it, and it's not intuitive whether declaring something to now be a dynamic-body thing brings in all of them and sets them all to default values - or what

**Comment by riebling** [comment]
```
AMQJS0005E Internal error. Error Message: data.shape is undefined, Stack trace: initBody@https://xr.andrew.cmu.edu/refactor/vendor/aframe-physics-system.js:17135:9
init@https://xr.andrew.cmu.edu/refactor/vendor/aframe-physics-system.js:17098:12
initComponent@https://xr.andrew.cmu.edu/refactor/aframe/dist/aframe-master.js:75943:10
updateProperties@https://xr.andrew.cmu.edu/refactor/aframe/dist/aframe-master.js:75925:12
[124]</module.exports.Component@https://xr.andrew.cmu.edu/refactor/aframe/dist/aframe-master.js:75701:8
NewComponent@https://xr.andrew.cmu.edu/refactor/aframe/dist/aframe-master.js:76285:15
value@https://xr.andrew.cmu.edu/refactor/aframe/dist/aframe-master.js:74447:19
value@https://xr.andrew.cmu.edu/refactor/aframe/dist/aframe-master.js:74610:12
[120]</proto<.setAttribute.value</<@https://xr.andrew.cmu.edu/refactor/aframe/dist/aframe-master.js:74842:14
onMessageArrived@https://xr.andrew.cmu.edu/refactor/mqtt.js:593:42
ClientImpl.prototype._receiveMessage@https://xr.andrew.cmu.edu/refactor/vendor/mqttws31.js:1397:9
ClientImpl.prototype._receivePublish@https://xr.andrew.cmu.edu/refactor/vendor/mqttws31.js:1372:10
ClientImpl.prototype._handleMessage@https://xr.andrew.cmu.edu/refactor/vendor/mqttws31.js:1248:10
ClientImpl.prototype._on_socket_message@https://xr.andrew.cmu.edu/refactor/vendor/mqttws31.js:1149:12
scope/<@https://xr.andrew.cmu.edu/refactor/vendor/mqttws31.js:157:13
```

**Comment by riebling** [comment]
Non-issue; this works if you set a-frame.js version to 0.9.2
